# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'HGPersonalCenter' do

  pod 'HGPersonalCenterExtend', '0.1.9'
  pod 'GKNavigationBarViewController', '2.2.5'

end
