# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'HGPersonalCenter' do

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'HGPersonalCenterExtend', '~> 0.1.3'

end
